services:
  # Nginx service
  school-web:
    image: nginx:alpine
    container_name: school-web
    restart: unless-stopped
    tty: true
    ports:
      - "8787:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - school-network

  # Laravel services
  school-app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      network: host
    image: school-app/php
    container_name: school-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - school-network

  # MySQL service
  school-db:
    image: mysql:5.7.22
    container_name: school-db
    restart: unless-stopped
    tty: true
    ports:
      - "33063:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - school-db:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - school-network

  # PHPMyAdmin service
  school-phpmyadmin:
    image: phpmyadmin
    container_name: school-phpmyadmin
    restart: unless-stopped
    tty: true
    ports:
      - "8383:80"
    environment:
      - PMA_HOST=school-db
    networks:
      - school-network

networks:
  school-network:
    driver: bridge

volumes:
  school-db:
    driver: local
